### ISSUE TITLE
Support all (most) features from avro-rs

### ISSUE THREAD

**Issue by flavray** [flavray/pyo3avro-rs#9]
As of now, only `Schema`s are available. It would be useful to have access to the whole avro-rs API.

**Comment by poros** [comment]
This one is proving to be too big for comfort. What about breaking it down in a list of features we need for running the benchmark for the talk and a list of features we are missing in general? An issue per feature or group of related features should be more manageable

**Comment by flavray** [comment]
Good point. 🙂
Closing this in favour of #16 #17 and #18 that should encapsulate most of the work required for this issue. We can create more later on if I missed something.
